export const deniedToasts = [
    'Denied with unnecessary confidence.',
    'Your disappointment has been filed.',
    'Reason: Too much enthusiasm.',
    'Klaus has reviewed this. Klaus is tired.',
    'Rejected. Please lower your expectations and try again.',
    'Stamp applied. Hope removed.',
    'Request denied. Your optimism has been noted and ignored.',
    'Outcome: Nein. Next window opens in 6–8 business years.',
    'This decision is final, unreadable, and slightly damp.',
    'Your application was processed by a man who sighed twice.',
    'Denied. Please take a number and lower your standards.',
    'Status: Abgelehnt. Have you tried being less hopeful?',
    'Klaus stamped it. The stamp was louder than your dreams.',
    'Rejected for reasons that will arrive by post in 4–6 weeks.',
    'Your request has been forwarded to the void.',
    'Outcome: Formally impossible. Emotionally expected.',
];

export const klausReplies = [
    'Unfortunately, no.',
    'I understand your need. Unfortunately, no.',
    'Please submit Form B-17 and lower your expectations.',
    'Your question has been forwarded to someone who is on vacation.',
    'Klaus has reviewed your request. Klaus regrets your optimism.',
    'That falls outside approved emotional parameters.',
    'Please rephrase your question as a complaint.',
    'Klaus is not a therapist. Klaus is a bureaucrat.',
    'That is not a question. That is a wish. Wishes require Form W-9.',
    'Klaus has noted your concern. Klaus has also noted his lunch break.',
    'Please wait 6–8 weeks. Then wait again.',
    'Your inquiry has been logged under “Unrealistic.”',
    'Klaus sympathizes. Sympathy is not approval.',
    'That request requires authorization from a department that no longer exists.',
    'Have you considered accepting the situation and making tea?',
    'Klaus cannot help you. Klaus can only redirect you.',
    'Your problem is valid. Your solution is not.',
    'Please submit in triplicate. Klaus will lose two copies anyway.',
];

export const calculatorResults = [
    'Unauthorized Happiness',
    'Pending Emotional Review',
    'Excessive Optimism Detected',
    'Application Spiritually Denied',
    'Form Incomplete. Soul Attachment Missing.',
    'Risk Level: Mildly Hopeful (Prohibited)',
    'Outcome: 0% Joy, 100% Paperwork',
    'Emotional Overdraft: Please Deposit Realism',
    'Status: Wartezeit Unbefristet',
    'Happiness Quotient Below Minimum Threshold',
    'Result: Nein (Rounded Down)',
    'Audit Finding: Too Much Personality',
    'Compliance Score: Acceptably Miserable',
    'Forecast: Cloudy With Stamp Errors',
    'Probability of Success: Statistically Rude',
    'Recommendation: Lower Ambitions, Raise Coffee Intake',
];

export const runningGagFacts = {
    divorce: [
        'Klaus still has a folder labeled “Scheidung — fast fertig”.',
        'His divorce mediator called the process “surprisingly organized”. Klaus cried.',
        'He signed page 41 with enthusiasm. Page 42 broke him.',
        'The settlement included custody of the good Tupperware.',
        'The wedding album lives in a box marked “Archiv — nicht öffnen”.',
        'He still has his ex’s spare house key. Neither knows why.',
        'Anniversary dates are blocked on his calendar as “Maintenance Day.”',
        'The divorce lawyer billed by the sigh.',
        'Klaus keeps the good wine glasses. She kept the wine.',
        'Their couples therapist retired. Klaus considered it a personal victory.',
        'He laminated the separation agreement. Twice. For safety.',
        'The mediator said “communicate.” Klaus sent a PDF.',
        'He refers to the divorce as “Phase Two of the Marriage Project.”',
        'Joint custody of the Netflix account was the hardest negotiation.',
    ],
    custody: [
        'Klaus calls his custody calendar “Project Emma-Lukas 50/50 Final_v7_REAL.xlsx”.',
        'Handover location: neutral parking lot, maximum awkwardness.',
        'Birthday parties require a shared Google Doc and a waiver.',
        'Emergency contact list includes his ex, his lawyer, and his therapist.',
        'Pickup time is 17:00. Klaus arrives at 16:47 and judges everyone.',
        'Weekend bags are packed with military precision and one forgotten sock.',
        'School reports are read, highlighted, and forwarded with commentary.',
        'Lukas forgot his toothbrush. Klaus issued a formal reminder.',
        'Emma’s phone has more apps than Klaus has filing cabinets.',
        'Handover small talk lasts exactly 47 seconds. Then silence.',
        'Klaus tracks expenses in a spreadsheet labeled “Kind — Kosten — Wahrheit.”',
        'Holiday schedules require a flowchart and a stiff drink.',
        'He once missed pickup because the printer jammed on a permission slip.',
        'Both kids know the phrase “Das steht nicht im Plan.”',
    ],
    car: [
        'His Skoda’s check engine light has been on since Merkel was Chancellor.',
        'The Octavia was declared dead three times. It continues out of spite.',
        'Klaus named his car “Projekt Zuverlässigkeit”. It has never forgiven him.',
        'The trunk contains one umbrella, two reflective vests, and eternal regret.',
        'The passenger seat holds a folder of unpaid parking tickets “for later.”',
        'He washes the car every Sunday. The check engine light watches in silence.',
        'The radio only plays news. Klaus considers this a feature.',
        'Winter tires go on in October. Summer tires go on when guilt arrives.',
        'He keeps a fire extinguisher, a first-aid kit, and three broken phone chargers.',
        'The fuel gauge lies. Klaus trusts the receipt more than the needle.',
        'He once parallel-parked perfectly and felt nothing. It was a Tuesday.',
        'The glove box contains registration papers and a single cough drop from 2018.',
        'Klaus talks to the car before long trips. The car does not answer.',
        'Every rattle has a name. None of them are good.',
    ],
    children: [
        'Lukas says “Digga.” Klaus responds with Form 12-C.',
        'Emma once corrected his Anlage numbering. Klaus was proud and horrified.',
        'Family dinner topics: recycling, homework, and administrative failures.',
        'Klaus’s Father’s Day gift was a laminated schedule. He loved it.',
        'Bedtime is 20:30. Negotiations open at 20:29.',
        'Lukas asked for a dog. Klaus presented a cost-benefit analysis.',
        'Emma’s school project was better organized than his quarterly reports.',
        'Screen time is tracked in a chart that would impress the Finanzamt.',
        'Klaus reads bedtime stories in a monotone that soothes and terrifies.',
        'Allowance is paid on time. With a receipt.',
        'He taught them to sort recycling before they could ride a bike.',
        'Homework help ends when Klaus starts citing paragraph numbers.',
        'Family meetings have an agenda. And minutes. And follow-up actions.',
        'Both kids know how to fill out a form. Klaus considers this parenting.',
    ],
    reihenhaus: [
        'Klaus once laminated a temporary note.',
        'The hedge is measured weekly. The feelings are not.',
        'Rain barrel maintenance is logged in a spreadsheet.',
        'Bins aligned like a military parade. Neighbors terrified.',
        'The garden gnome faces the street with the expression of a man who has seen things.',
        'He painted the fence beige. The neighbors painted theirs beige-er.',
        'The doorbell camera has seen more drama than his marriage.',
        'Klaus knows every car on the street by license plate and parking violation.',
        'The attic contains Christmas decorations and one box labeled “Später.”',
        'He mows the lawn in straight lines. The universe rewards him with nothing.',
        'Neighborhood WhatsApp group: muted since 2019. Klaus checks it anyway.',
        'The welcome mat says “Willkommen.” Klaus means it conditionally.',
        'He filed a noise complaint about a bird. The bird won on appeal.',
        'The Reihenhaus rules are laminated and posted inside the pantry door.',
    ],
    recycling: [
        'Klaus has more bin categories than emotions.',
        'Pfand returns are treated as a spiritual practice.',
        'He once argued with a neighbor about yogurt lid classification.',
        'Biomüll shame occurs every Tuesday at 07:00 sharp.',
        'Yellow bag day is a religious holiday in the Müller household.',
        'He returns bottles in alphabetical order. The cashier fears him.',
        'One wrong item in the Gelbe Tonne ruins Klaus’s entire week.',
        'He keeps a laminated guide to packaging symbols in his wallet.',
        'The Restmüll bin is always suspiciously light. Klaus suspects sabotage.',
        'Glass recycling is sorted by color. Emotions are not.',
        'He once drove 12 km to the correct Wertstoffhof. It was worth it.',
        'Neighbors ask Klaus before throwing anything away. He does not enjoy this.',
        'Pfand receipts are filed under “Liquid Assets.”',
        'Biomüll smells like failure. Klaus accepts this.',
    ],
    vacation: [
        'Same Baltic Sea trip every year. Same apartment. Same disappointment.',
        'Klaus calls it “adventure.” The GPS disagrees.',
        'Beach towel position documented with photographic evidence.',
        'Weather forecast: cloudy with a chance of administrative regret.',
        'The suitcase is packed three days early. Anxiety packed first.',
        'He brings his own coffee. The Baltic Sea cannot be trusted.',
        'Sunscreen application follows a documented procedure.',
        'The holiday photos are sorted by date, location, and cloud coverage.',
        'Rain on day one is logged as “expected variance.”',
        'He reads the Ferienwohnung rules more carefully than the view.',
        'The minigolf scorecard is kept for historical records.',
        'Klaus packed a portable document scanner. Just in case.',
        'Return journey begins with a traffic jam. Klaus nods. Of course.',
        'Vacation debrief happens over Abendbrot on day one back.',
    ],
    office: [
        'Klaus is not powerful. He is middle management with a stamp.',
        'His greatest authority: rejecting your stapler request.',
        'Meeting about meetings: attended. Survived. Barely.',
        'Reply-all disasters are his origin story.',
        'His desk drawer contains three pens, one that works, and despair.',
        'The coffee machine broke in 2021. Klaus still reports it weekly.',
        'He cc’s himself on emails for “documentation purposes.”',
        'Lunch break: 12:00–12:30. Soul break: ongoing since 2009.',
        'The org chart shows him three levels from anyone who can help.',
        'His out-of-office message is longer than most novels.',
        'He once approved something by accident. He still thinks about it.',
        'The break room microwave has a sign Klaus wrote. Nobody reads it.',
        'Performance reviews describe him as “reliable” and “deeply tired.”',
        'He keeps a rubber stamp that says NEIN. It is his most-used tool.',
    ],
    food: [
        'Abendbrot is not a meal. It is a lifestyle.',
        'Potato salad prepared with emotional restraint.',
        'Coffee number four: still tired, slightly more bureaucratic.',
        'His spice rack contains salt, pepper, and resignation.',
        'Brötchen are purchased Saturday morning. Devoured by Saturday afternoon.',
        'Klaus eats standing up when stressed. He is always slightly stressed.',
        'The freezer contains four identical frozen pizzas and one mystery container.',
        'He measures Milch for coffee. Feelings are not measured.',
        'Restaurant menus overwhelm him. He orders the Schnitzel. Always.',
        'Leftovers are labeled with date, contents, and expiration anxiety.',
        'His favorite recipe is “whatever is in the Kühlschrank.”',
        'Kaffee und Kuchen on Sunday is non-negotiable. The Kuchen is store-bought.',
        'He once brought Tupperware to a wedding reception. Prepared, not rude.',
        'Breakfast is functional. Lunch is forgotten. Abendbrot is sacred.',
    ],
    technology: [
        'Klaus trusts PDF. Everything else is suspicious.',
        'His idea of flirting is forwarding a PDF without being asked.',
        'Cloud storage is “where files go to die”.',
        'Printer driver trauma: ongoing since 2019.',
        'He owns three folders labeled “Miscellaneous” and trusts none of them.',
        'His password is written on a sticky note inside a locked drawer.',
        'Software updates are postponed until something breaks critically.',
        'He still has a fax number. He checks it monthly. Nothing.',
        'Two-factor authentication confuses him. One-factor bureaucracy does not.',
        'His desktop has 47 icons. He uses four. He will not delete the rest.',
        'He prints emails “for the record.” The record is a filing cabinet.',
        'Zoom meetings require 15 minutes of technical preparation and one deep breath.',
        'He backup his backups. The backups are also PDFs.',
        'Smart home devices are “unnecessary surveillance.” The doorbell camera disagrees.',
    ],
};
